### PR TITLE
Update FrameList.cpp 

### PR DESCRIPTION
**Pull request by Kevin-Dorscher**
Changed the AddNode function to insert to the tail of the linked list.
I can add more functions to delete a node at the nth position, and add a node at the nth position
after we figure out how we want to do our file i/o.

### CODE REVIEW

**Comment by Cyberzoid1** [comment]
I would vote to revert this commit and have you add a method AddNode_end or AddEndNode (or simular)
That way we have both functions

On a design note: you can use the tail pointer to add directly to the end. No need to travers down the entire list to get to the end.

**Comment by Cyberzoid1** [comment]
You will have to add a 
`NodePtr tail;` to FrameList.h

**Comment by Kevin-Dorscher** [comment]
I didn't do this initally because traversing the list no matter how its done is always going to have the efficiency class of O(n). Also, the only time you would not add to the tail of the list is when the list is empty, so to me it doesn't really make sense to have a Add_to_head fucntion as this would only ever be called once, and every other time a new node is added you would call the Add_to_tail function so it makes more sense in my mind to account for the Add_to_head case so any node added to the list can be done in 1 nice convient function.

**Comment by Cyberzoid1** [comment]
True. and I suppose I can accept that. 
Still adding to tail is O(1) not O(n) if you use the tail pointer.

**Pull request merged**
